name: makeeasy
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  flutter_markdown: ^0.6.23
  camera: ^0.11.1
  camera_android: ^0.10.10+1
  google_mlkit_face_mesh_detection: ^0.4.1
  google_mlkit_commons: ^0.11.0
  vector_math: ^2.1.4
  image: ^4.1.3 # For image conversion
  tuple: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

fonts:
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat-Regular.ttf
      - asset: fonts/Montserrat-Bold.ttf
        style: bold
      - asset: fonts/Montserrat-Italic.ttf
        style: italic

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/lippie_logo.png
    - assets/images/dummylook1.jpg
    - assets/images/profile.jpg
