name: makeeasy
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.0.2
  http: ^1.4.0
  flutter_markdown: ^0.7.7+1
  camera: ^0.11.1
  camera_android: ^0.10.10+1
  google_mlkit_face_mesh_detection: ^0.4.1
  google_mlkit_commons: ^0.11.0
  vector_math: ^2.1.4
  image: ^4.1.3 # For image conversion
  tuple: ^2.0.0
  provider: ^6.1.5
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  tutorial_coach_mark: ^1.3.0
  flutter_staggered_animations: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

fonts:
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat-Regular.ttf
      - asset: fonts/Montserrat-Bold.ttf
        style: bold
      - asset: fonts/Montserrat-Italic.ttf
        style: italic

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/lippie_logo.png
    - assets/images/dummylook1.jpg
    - assets/images/profile.jpg
    - assets/images/daily.png
    - assets/images/party.png
