// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbdYGT5IBEPBGOuV4i5kLR1DuIV960EnM',
    appId: '1:629688799047:web:808e39cb8f7d9f69cdc662',
    messagingSenderId: '629688799047',
    projectId: 'ss-makeeasy',
    authDomain: 'ss-makeeasy.firebaseapp.com',
    storageBucket: 'ss-makeeasy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKuXF85LTkbYkRtjzIIUGAwILJabEM65Y',
    appId: '1:629688799047:android:a8034c75e822be87cdc662',
    messagingSenderId: '629688799047',
    projectId: 'ss-makeeasy',
    storageBucket: 'ss-makeeasy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ0jTlDW-Oqf-0CUEMWPEnqG2jluwwNR4',
    appId: '1:629688799047:ios:469fcb3be750f538cdc662',
    messagingSenderId: '629688799047',
    projectId: 'ss-makeeasy',
    storageBucket: 'ss-makeeasy.firebasestorage.app',
    iosBundleId: 'com.example.makeeasy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbdYGT5IBEPBGOuV4i5kLR1DuIV960EnM',
    appId: '1:629688799047:web:04bc9002e6aadb43cdc662',
    messagingSenderId: '629688799047',
    projectId: 'ss-makeeasy',
    authDomain: 'ss-makeeasy.firebaseapp.com',
    storageBucket: 'ss-makeeasy.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ0jTlDW-Oqf-0CUEMWPEnqG2jluwwNR4',
    appId: '1:629688799047:ios:469fcb3be750f538cdc662',
    messagingSenderId: '629688799047',
    projectId: 'ss-makeeasy',
    storageBucket: 'ss-makeeasy.firebasestorage.app',
    iosBundleId: 'com.example.makeeasy',
  );

}